version: '3.7'
services: 
    app:  
        container_name: redis-template
        build: . 
        ports:
            - "80:80"
        depends_on:
            - redis
    redis:
        image: redis:alpine